
# Website info
name: 'Finding The Way Home'
description: "A beautiful narrative written with the world's most elegant publishing platform. The story begins here."

# Author's info
author: 'Casper McFadden'
username: casper
bio: 'A paranormal expert and his daughter bunk in an abandoned house populated by 3 mischievous ghosts and one friendly one.'
location: 'Maine, USA'
url: 'http://biomadeira.github.io/jasper/'
image: 'assets/images/casper.png'

# Jykell configuration
markdown: redcarpet
highlighter: pygments
paginate: 5
language: 'en-uk'
short_url: 'biomadeira.github.io/jasper'
google_analytics: 'UA-XXXXXXXX-X'
disqus: biomadeira

# this is a fix to properly run jasper on top of my personal
# biomadeira.github.io - all contents run on /jasper/
# for a normal use at the base of the server change it to "/"
baseurl: biomadeira.github.io/jasper/

# Permalinks
permalink: /:title
# permalink: /author/:username
# permalink: /tag/:tag

# Additional settings available on the front-matter
# Site logo in the index.html (as in demo.ghost.io)
# Author's page cover in _layouts/author.html
# The same for page.html and tag.html layouts
# Post's page cover as a per-post basis _posts/...
# Disqus comments as a per-post basis
# ...

